# yaml-language-server: $schema=https://gist.githubusercontent.com/bcho/e19fa748745a985aa7393530acff24fa/raw/c7a653834a117405c3dfbcd60cccc94949d3ef3f/forge-devkit-component.json
apiVersion: v1alpha1
kind: Component
metadata:
  name: guestbook
profiles:
  - name: default
    kubernetes:
      pod:
        name: guestbook
        mainEntryContainerImage: forgedev.azurecr.io/devkit-containers/go:v2022100301
      patches:
        - # below is to create the dev pod from existing application pod. Please edit the label selector to match the application pod
          clonePod:
            selector:
              matchLabels:
                control-plane: controller-manager
        - # below is to patch the dev pod using strategic merge. Please edit the patch file to match your needs
          patchesStrategicMerge:
            - pod-patch.yaml
