---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-webapp-forge-dev-v1-guestbook
  failurePolicy: Fail
  name: mguestbook.kb.io
  rules:
  - apiGroups:
    - webapp.forge.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - guestbooks
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-webapp-forge-dev-v1-guestbook
  failurePolicy: Fail
  name: vguestbook.kb.io
  rules:
  - apiGroups:
    - webapp.forge.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - guestbooks
  sideEffects: None
